# Generated by Django 4.2.20 on 2025-04-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='title',
            field=models.CharField(default='Untitled Entry', max_length=200),
        ),
    ]
